name: Java CI

on:
  push:
    branches:
      - main
      - devops/docker

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Make Maven Wrapper executable
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # 4. Run tests
      - name: Run tests
        run: ./mvnw test

      # 5. Build Spring Boot application
      - name: Build application
        run: ./mvnw clean package -DskipTests

      # 6. Build backend Docker image
      - name: Build backend Docker image
        run: docker build -t ecommerce-backend:ci .

      # 7. Build frontend Docker image
      - name: Build frontend Docker image
        run: docker build -t ecommerce-frontend:ci ./ecommerce-frontend